/*
 * Config.h
 *
 *  Created on: 2015-11-5
 *      Author: hsy
 */

#ifndef CONFIG_H_
#define CONFIG_H_


// TAGs
const int TAG_ENEMY = 100;
const int TAG_HERO = 200;
const int TAG_BULLET = 300;
const int TAG_SUPPLY = 500;

// Physical related
const int PHYSICAL_BODY_HERO_GROUP = -1;
const int PHYSICAL_BODY_HERO_BITMASK_CATEGORY = 1;
const int PHYSICAL_BODY_HERO_BITMASK_CONTACT_TEST = 12;
const int PHYSICAL_BODY_HERO_BITMASK_COLLISION = 12;

const int PHYSICAL_BODY_BULLET_GROUP = -2;
const int PHYSICAL_BODY_BULLET_BITMASK_CATEGORY = 2;
const int PHYSICAL_BODY_BULLET_BITMASK_CONTACT_TEST = 8;
const int PHYSICAL_BODY_BULLET_BITMASK_COLLISION = 8;

const int PHYSICAL_BODY_SUPPLY_GROUP = -3;
const int PHYSICAL_BODY_SUPPLY_BITMASK_CATEGORY = 4;
const int PHYSICAL_BODY_SUPPLY_BITMASK_CONTACT_TEST = 1;
const int PHYSICAL_BODY_SUPPLY_BITMASK_COLLISION = 1;

const int PHYSICAL_BODY_ENEMY_GROUP = -4;
const int PHYSICAL_BODY_ENEMY_BITMASK_CATEGORY = 8;
const int PHYSICAL_BODY_ENEMY_BITMASK_CONTACT_TEST = 3;
const int PHYSICAL_BODY_ENEMY_BITMASK_COLLISION = 3;


#endif /* CONFIG_H_ */
